ClosestAddress/ClosestAddress/Controllers/ClosestAddressController.cs
using System.Web.Mvc;

namespace ClosestAddress.Controllers
{
    public class ClosestAddressController : Controller
    {
        /// <summary>
        /// Index page of ClosestAddress 
        /// </summary>
        /// <returns>ActionResult</returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

ClosestAddress/ClosestAddress/Views/ClosestAddress/Index.cshtml
@{
    ViewBag.Title = "Closest Address";
}
<div class="container" id="closest-address-results" data-dataURL="http://closestaddressapi/api/ClosestAddressWebapi">
    <div class="row">
        <div class="col-lg-12">
            <h2>Find Closest Address</h2>
            <div class="alert alert-danger" v-if="isDisplayMessage">
                <strong>Please enter address</strong>
            </div>
            <div class="form-group">
                <label for="address">Address:</label>
                <input name="address" type="text" class="form-control" value="" id="txtAddress" v-model="searchAddress" />
            </div>
            <input type="button" value="Submit" id="btnSearch" class="btn btn-primary" v-on:click="searchClick" />
        </div>
    </div>
    <div class="table-responsive" v-if="results.length>0">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>KM</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="address in results">
                    <td>{{address.Name}}</td>
                    <td>{{address.KM}}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="overlay" v-if="isDisplayLoader">
        <a href="javascript:void(0)" class="closebtn"></a>
        <div class="overlay-content">
            Loading...
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/closestaddress")

ClosestAddress/ClosestAddress/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/vue")
    @Scripts.Render("~/bundles/axios")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Closest Address Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Closest Address", "Index", "ClosestAddress")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>